"""WP-2: the agent supervisor's Python core (thin, stdlib-only, no daemon).

The supervisor itself is an EXTERNAL script the operator runs (generated by
``agenttalk supervise --init``); it owns launching/killing/relaunching agent
terminals and tracking the PIDs it launched. THIS module owns everything that
must be deterministic and CI-testable WITHOUT launching a terminal:

- :func:`build_report` — the read-only bus-side liveness snapshot
  (``agenttalk supervise --report --json``).
- :func:`plan_actions` — the SHARED decision table. Given the report, the
  supervisor's own state (launched-pid liveness + backoff + consumed restart
  ids + last-warn timestamps), and config, it returns one safe ACTION per
  agent PLUS the next state. The live loop and the ``--dry-run`` harness call
  the SAME function, so the safety table is unit-tested via fixtures and never
  depends on real process death.

Decision principle (codex's scout): the ONLY auto-restart trigger is death of
the process the supervisor launched (the script reports ``pid_alive``). A stale
heartbeat is SUSPECT/WARN-only — never an auto-kill — because a healthy agent
mid-long-turn does not heartbeat.
"""

from __future__ import annotations

from datetime import datetime, timezone

from agenttalk.store import Store, _process_alive

# ---- action vocabulary (the dry-run ACTION PLAN tokens) --------------------
RELAUNCH = "relaunch"            # (re)launch the agent now
BACKOFF_WAIT = "backoff_wait"    # dead + unprotected but still inside backoff
WARN_ONLY = "warn_only"          # protected agent died — warn/note, never relaunch
REFUSE_PROTECTED = "refuse_protected"  # manual restart of a protected agent w/o --force-protected
SUSPECT_WARN = "suspect_warn"    # alive but heartbeat stale — warn, never kill
CLEAR_MARKER = "clear_marker"    # a consumed restart marker on a now-healthy agent: just clear it
NONE = "none"                    # healthy, nothing to do

# Default cadence knobs (config overrides these).
_DEFAULTS = {
    "poll_seconds": 15,
    "suspect_after_seconds": 120,
    "suspect_warn_interval_seconds": 300,
    "backoff": {"base_seconds": 30, "cap_seconds": 900, "reset_after_seconds": 180},
}


def _backoff_cfg(config: dict) -> dict:
    b = dict(_DEFAULTS["backoff"])
    raw = config.get("backoff") if isinstance(config.get("backoff"), dict) else {}
    for k in b:
        if isinstance(raw.get(k), (int, float)):
            b[k] = raw[k]
    return b


def build_report(store: Store, *, now_epoch: float,
                 suspect_after_seconds: float | None = None) -> dict:
    """Point-in-time bus-side liveness snapshot. Read-only.

    ``protected`` is ``operator_facing`` UNION every active ``role=lead`` agent
    (fail-closed — see ``Store.protected_agents``). ``heartbeat_stale`` is
    True when there is no heartbeat or it is older than ``suspect_after_seconds``.
    The launched-PID liveness is NOT here — only the script knows it.
    """
    if suspect_after_seconds is None:
        suspect_after_seconds = float(_DEFAULTS["suspect_after_seconds"])
    cfg = store.load_config()
    roster = cfg.get("agents", []) or []
    roles = cfg.get("roles") or {}
    protected = store.protected_agents()
    agents: dict[str, dict] = {}
    for a in roster:
        hb = store.read_heartbeat(a)
        if hb is None:
            hb_age = None
            stale = True
        else:
            hb_age = max(0.0, now_epoch - hb.timestamp())
            stale = hb_age > suspect_after_seconds
        marker = store.read_waiting(a)
        w_pid = marker.get("pid") if isinstance(marker, dict) else None
        w_pid = w_pid if isinstance(w_pid, int) else None
        agents[a] = {
            "role": roles.get(a) if isinstance(roles.get(a), str) else None,
            "protected": a in protected,
            "heartbeat_age_seconds": hb_age,
            "heartbeat_stale": stale,
            "waiting": marker is not None,
            "waiting_pid": w_pid,
            "waiting_pid_alive": bool(w_pid is not None and _process_alive(w_pid)),
            "waiting_deadline_epoch": (marker.get("deadline_epoch")
                                       if isinstance(marker, dict) else None),
            "restart_request": store.read_restart_request(a),
        }
    return {
        "schema_version": 1,
        "now_epoch": now_epoch,
        "now": datetime.fromtimestamp(now_epoch, timezone.utc).isoformat().replace(
            "+00:00", "Z"),
        "roster": list(roster),
        "operator_facing": store.operator_facing(),
        "sole_lead": store.sole_lead(),
        "suspect_after_seconds": suspect_after_seconds,
        "agents": agents,
    }


def _plan_one(name: str, rpt: dict, st: dict, config: dict,
              *, now_epoch: float) -> dict:
    """Decide ONE agent's action + next state. Pure — no I/O, no clock."""
    backoff = _backoff_cfg(config)
    suspect_interval = float(config.get(
        "suspect_warn_interval_seconds", _DEFAULTS["suspect_warn_interval_seconds"]))
    reset_after = float(backoff["reset_after_seconds"])

    protected = bool(rpt.get("protected"))
    pid_alive = bool(st.get("pid_alive", False))
    marker = rpt.get("restart_request") or None
    consumed = list(st.get("consumed_rids", []))
    fails = int(st.get("consecutive_fails", 0))
    backoff_next = float(st.get("backoff_next_epoch", 0.0) or 0.0)
    healthy_since = st.get("healthy_since")
    last_warn = float(st.get("last_warn_epoch", 0.0) or 0.0)

    # carry-forward state; mutated per branch below
    nxt = {
        "consecutive_fails": fails,
        "backoff_next_epoch": backoff_next,
        "healthy_since": healthy_since,
        "consumed_rids": consumed,
        "last_warn_epoch": last_warn,
    }

    def _relaunch_state() -> None:
        nf = fails + 1
        delay = min(float(backoff["cap_seconds"]),
                    float(backoff["base_seconds"]) * (2 ** (nf - 1)))
        nxt["consecutive_fails"] = nf
        nxt["backoff_next_epoch"] = now_epoch + delay
        nxt["healthy_since"] = None

    def _result(action, **detail):
        return {"agent": name, "action": action,
                "clear_marker": detail.get("clear_marker"),
                "kill_first": bool(detail.get("kill_first", False)),
                "bypass_backoff": bool(detail.get("bypass_backoff", False)),
                "notify": bool(detail.get("notify", False)),
                "reason": detail.get("reason", ""),
                "next_state": nxt}

    # 1) Manual restart-request marker (highest priority).
    if isinstance(marker, dict) and isinstance(marker.get("request_id"), str):
        rid = marker["request_id"]
        forced = bool(marker.get("force_protected"))
        if protected and not forced:
            nxt["last_warn_epoch"] = now_epoch
            return _result(REFUSE_PROTECTED, clear_marker=rid, notify=True,
                           reason="restart of a protected agent requires "
                                  "--force-protected")
        if rid not in consumed:
            # Honor once: bypass backoff, kill a still-alive process first.
            nxt["consumed_rids"] = [*consumed, rid]
            _relaunch_state()
            return _result(RELAUNCH, clear_marker=rid, kill_first=pid_alive,
                           bypass_backoff=True,
                           reason=f"manual restart-request {rid}")
        # Already consumed this rid:
        if pid_alive:
            # the relaunch took — just clean up the (stale) marker.
            return _result(CLEAR_MARKER, clear_marker=rid,
                           reason=f"restart {rid} already applied; clearing marker")
        # consumed but still dead -> the relaunch FAILED. Do NOT bypass again
        # and do NOT silently clear; fall through to the backoff-gated path.

    # 2) Supervised process is dead.
    if not pid_alive:
        if protected:
            nxt["last_warn_epoch"] = now_epoch
            return _result(WARN_ONLY, notify=True,
                           reason="protected agent died — restart it manually "
                                  "(or use request-restart --force-protected)")
        if now_epoch >= backoff_next:
            _relaunch_state()
            return _result(RELAUNCH, reason="supervised process died")
        return _result(BACKOFF_WAIT,
                       reason=f"dead; backing off until {backoff_next:.0f}")

    # 3) Alive but heartbeat stale (and not legitimately blocked in a wait).
    if rpt.get("heartbeat_stale") and not rpt.get("waiting_pid_alive"):
        if now_epoch - last_warn >= suspect_interval:
            nxt["last_warn_epoch"] = now_epoch
            return _result(SUSPECT_WARN,
                           reason="heartbeat stale; agent may be wedged "
                                  "(NOT auto-killed — could be mid-long-turn)")
        return _result(NONE, reason="suspect (warn rate-limited)")

    # 4) Healthy. Advance/trip the sustained-liveness backoff reset.
    if healthy_since is None:
        nxt["healthy_since"] = now_epoch
    elif fails and (now_epoch - float(healthy_since)) >= reset_after:
        nxt["consecutive_fails"] = 0
        nxt["backoff_next_epoch"] = 0.0
    return _result(NONE, reason="healthy")


def plan_actions(report: dict, state: dict, config: dict,
                 *, now_epoch: float) -> dict:
    """The SHARED decision table. Returns ``{"now_epoch", "agents": {name: plan}}``
    where each plan has ``action`` (one of the module's action constants),
    ``clear_marker``/``kill_first``/``bypass_backoff``/``notify``/``reason``,
    and ``next_state`` for the supervisor to persist. Only agents present in
    BOTH the config and the report are planned (config drives what is
    supervised; the report supplies bus facts)."""
    cfg_agents = config.get("agents") if isinstance(config.get("agents"), dict) else {}
    rpt_agents = report.get("agents") or {}
    state_agents = state.get("agents") if isinstance(state.get("agents"), dict) else {}
    out: dict[str, dict] = {}
    for name, cfg_agent in cfg_agents.items():
        if not isinstance(cfg_agent, dict) or not cfg_agent.get("auto_restart", False):
            continue
        rpt = rpt_agents.get(name)
        if not isinstance(rpt, dict):
            continue
        st = state_agents.get(name) if isinstance(state_agents.get(name), dict) else {}
        out[name] = _plan_one(name, rpt, st, config, now_epoch=now_epoch)
    return {"now_epoch": now_epoch, "agents": out}


# --------------------------------------------------------------- init / scaffold

CONFIG_TEMPLATE = """\
{
  "schema_version": 1,
  "poll_seconds": 15,
  "suspect_after_seconds": 120,
  "suspect_warn_interval_seconds": 300,
  "backoff": { "base_seconds": 30, "cap_seconds": 900, "reset_after_seconds": 180 },
  "notify_sender": null,
  "notify_to": null,
  "agents": {
    "AGENT_NAME": {
      "auto_restart": true,
      "auto_restart_protected": false,
      "cwd": "REPLACE_WITH_PROJECT_DIR",
      "env": { "AGENTTALK_SELF": "AGENT_NAME" },
      "pid_strategy": "launched-process",
      "launch": {
        "windows": "EXAMPLE: Start-Process powershell.exe -PassThru -ArgumentList '-NoLogo','-NoExit','-Command','<your agent CLI here>'",
        "posix": "EXAMPLE: setsid <your agent CLI here> >\\"$cwd/agent.log\\" 2>&1 & echo $!"
      }
    }
  }
}
"""

# NOTE on the templates below: the DECISION lives in Python
# (`agenttalk supervise --plan`); the scripts are THIN executors that supply
# launched-pid liveness, run the plan, and do terminal mechanics. They support
# `--once --dry-run` to print the action plan without launching anything.

PS_TEMPLATE = r"""# agenttalk supervisor (PowerShell) — generated by `agenttalk supervise --init`.
# The DECISION table is in Python (`agenttalk supervise --plan`); this script
# only tracks launched PIDs, runs the plan, and launches/kills terminals.
#   .\supervisor.ps1                 # run the monitor loop
#   .\supervisor.ps1 -Once -DryRun   # print the action plan once, change nothing
param([switch]$Once, [switch]$DryRun)
$ErrorActionPreference = 'Stop'
$Root      = Split-Path -Parent $PSScriptRoot   # the project root (.agenttalk/..)
$ConfigPath = Join-Path $PSScriptRoot 'supervisor.json'
$StatePath  = Join-Path $PSScriptRoot 'supervisor-state.json'   # SCRIPT-owned, not the bus
$cfg = Get-Content $ConfigPath -Raw | ConvertFrom-Json

function Load-State {
  if (Test-Path $StatePath) { return (Get-Content $StatePath -Raw | ConvertFrom-Json) }
  return [pscustomobject]@{ agents = [pscustomobject]@{} }
}
function Save-State($state) { $state | ConvertTo-Json -Depth 8 | Set-Content $StatePath -Encoding utf8 }
function Pid-Alive($procId) {
  if (-not $procId) { return $false }
  return [bool](Get-Process -Id $procId -ErrorAction SilentlyContinue)
}
function Launch($name) {
  $a = $cfg.agents.$name
  if (-not $a.launch.windows -or $a.launch.windows -like 'EXAMPLE:*') {
    Write-Warning "supervisor: agent '$name' has no real launch.windows command — fill supervisor.json"; return $null
  }
  # Operator-provided command MUST yield a monitorable PID (Start-Process -PassThru).
  # Do NOT use wt.exe: a wt tab process exits right after spawning the shell, so
  # its PID dies immediately and death-detection would loop-restart forever.
  $p = Invoke-Expression $a.launch.windows
  if ($p -and $p.Id) { return $p.Id }
  Write-Warning "supervisor: launch of '$name' returned no PID (need Start-Process -PassThru); auto-restart disabled for it"; return $null
}

do {
  $state = Load-State
  if (-not $state.agents) { $state | Add-Member agents ([pscustomobject]@{}) -Force }
  # 1) refresh launched-pid liveness into the state the planner reads
  foreach ($name in $cfg.agents.PSObject.Properties.Name) {
    $st = $state.agents.$name; if (-not $st) { $st = [pscustomobject]@{}; $state.agents | Add-Member $name $st -Force }
    $procId = $st.pid; $st | Add-Member pid_alive (Pid-Alive $procId) -Force
  }
  Save-State $state
  # 2) ask Python for the safe action plan
  $now = [int][double]::Parse((Get-Date -UFormat %s))
  $plan = (& agenttalk --root $Root supervise --plan --state-file $StatePath --now $now) | ConvertFrom-Json
  foreach ($name in $plan.agents.PSObject.Properties.Name) {
    $p = $plan.agents.$name
    if ($DryRun) { Write-Host ("{0}: {1} — {2}" -f $name, $p.action, $p.reason); continue }
    switch ($p.action) {
      'relaunch' {
        if ($p.kill_first -and (Pid-Alive $state.agents.$name.pid)) { Stop-Process -Id $state.agents.$name.pid -Force -ErrorAction SilentlyContinue }
        $newPid = Launch $name
        $ns = $p.next_state
        if ($newPid) {
          $ns | Add-Member pid $newPid -Force; $ns | Add-Member pid_alive $true -Force
          $state.agents.$name = $ns
          # Clear the manual marker ONLY after a CONFIRMED relaunch (a $null
          # PID = no/invalid launch command) — never silently drop a request
          # whose relaunch failed; it must remain for the next poll to retry.
          if ($p.clear_marker) { & agenttalk --root $Root supervise --clear-restart --for $name --request-id $p.clear_marker | Out-Null }
        } else {
          Write-Warning ("supervisor: {0}: relaunch FAILED (no PID) — keeping restart marker for retry" -f $name)
          $state.agents.$name = $ns
        }
      }
      'clear_marker' { if ($p.clear_marker) { & agenttalk --root $Root supervise --clear-restart --for $name --request-id $p.clear_marker | Out-Null }; $state.agents.$name = $p.next_state }
      'refuse_protected' { Write-Warning ("supervisor: {0}: {1}" -f $name, $p.reason); if ($p.clear_marker) { & agenttalk --root $Root supervise --clear-restart --for $name --request-id $p.clear_marker | Out-Null }; $state.agents.$name = $p.next_state }
      { $_ -in 'warn_only','suspect_warn' } {
        Write-Warning ("supervisor: {0}: {1}" -f $name, $p.reason)
        if ($p.notify -and $cfg.notify_sender -and $cfg.notify_to) {
          & agenttalk --root $Root send --from $cfg.notify_sender --to $cfg.notify_to --kind note -m ("supervisor: {0}: {1}" -f $name, $p.reason) --quiet | Out-Null
        }
        $state.agents.$name = $p.next_state
      }
      default { $state.agents.$name = $p.next_state }
    }
  }
  if (-not $DryRun) { Save-State $state }
  if (-not $Once) { Start-Sleep -Seconds ([int]$cfg.poll_seconds) }
} while (-not $Once)
"""

def init(store: Store, *, force: bool = False) -> dict:
    """Scaffold the supervisor config + PowerShell script under ``.agenttalk/``.
    Returns ``{path: "written"|"exists"}``. Never overwrites without ``force``
    (the config especially — it holds the operator's filled-in launch commands).

    v1 ships the PowerShell supervisor only (the operator is on Windows); a
    POSIX (bash) supervisor is a documented follow-up — the Python core
    (``supervise --report``/``--plan``, ``request-restart``) is already
    cross-platform, so a future ``supervisor.sh`` is a thin add.
    """
    out: dict[str, str] = {}
    targets = {
        store.dir / "supervisor.json": CONFIG_TEMPLATE,
        store.dir / "supervisor.ps1": PS_TEMPLATE,
    }
    for path, content in targets.items():
        if path.exists() and not force:
            out[str(path)] = "exists"
            continue
        path.write_text(content, encoding="utf-8")
        out[str(path)] = "written"
    return out
