"""WP-2: the agent supervisor's Python core (thin, stdlib-only, no daemon).

The supervisor itself is an EXTERNAL script the operator runs (generated by
``agenttalk supervise --init``); it owns launching/killing/relaunching agent
terminals and tracking the PIDs it launched. THIS module owns everything that
must be deterministic and CI-testable WITHOUT launching a terminal:

- :func:`build_report` - the read-only bus-side liveness snapshot
  (``agenttalk supervise --report --json``).
- :func:`plan_actions` - the SHARED decision table. Given the report, the
  supervisor's own state (launched-pid liveness + backoff + consumed restart
  ids + last-warn timestamps), and config, it returns one safe ACTION per
  agent PLUS the next state. The live loop and the ``--dry-run`` harness call
  the SAME function, so the safety table is unit-tested via fixtures and never
  depends on real process death.

Decision principle (codex's scout, extended in WP-3): a DEAD supervised process
is relaunched; an ALIVE process whose ACTIVITY heartbeat has gone stale is
STUCK and recovered (kill + resume) - but ONLY when the activity hook is
installed for that agent (``activity_hook``), because without it we cannot
tell "stuck" from "busy mid-long-turn" and a stale heartbeat falls back to
warn-only (``suspect_warn``, never a kill). Protected agents are never
auto-killed (warn-only). Every relaunch resumes the pinned session so context
is preserved across a force-kill.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone

from agenttalk.store import Store, _process_alive

# ---- action vocabulary (the dry-run ACTION PLAN tokens) --------------------
RELAUNCH = "relaunch"            # DEAD process - (re)launch now (resume session)
STUCK_RECOVER = "stuck_recover"  # ALIVE but activity-stale + hook on - kill + resume
BACKOFF_WAIT = "backoff_wait"    # dead/stuck + unprotected but still inside backoff
WARN_ONLY = "warn_only"          # protected agent died/stuck - warn/note, never kill
REFUSE_PROTECTED = "refuse_protected"  # manual restart of a protected agent w/o --force-protected
SUSPECT_WARN = "suspect_warn"    # alive + stale but NO activity hook - warn, never kill
CLEAR_MARKER = "clear_marker"    # a consumed restart marker on a now-healthy agent: just clear it
NONE = "none"                    # healthy, nothing to do

# Default cadence knobs (config overrides these).
_DEFAULTS = {
    "poll_seconds": 15,
    "stuck_after_seconds": 120,            # alive + heartbeat older than this = stuck
    "suspect_warn_interval_seconds": 300,  # rate-limit for the no-hook warn fallback
    "backoff": {"base_seconds": 30, "cap_seconds": 900, "reset_after_seconds": 180},
}

# Per-CLI session-argument templates, as LISTS of literal tokens (so the
# generated PowerShell uses an array-of-literals ArgumentList - single-quoted
# PS literals do NOT expand `$`, so the Codex `$agenttalk-listen` prompt and
# any token survive intact, sidestepping the quote-nesting + $-expansion
# hazards codex flagged). The launch PROMPT is the EXPLICIT listen skill for
# BOTH fresh and resume (a fresh session has no context, so prose won't enter
# listen mode): Claude `/agenttalk.listen`, Codex `$agenttalk-listen`.
# {SESSION_ID} is filled by Python for resume, or by the script (claude only)
# after it mints a uuid. Operator-overridable per agent via
# config["agents"][n]["session"]["fresh"|"resume"] (a token list).
_SESSION_DEFAULTS = {
    "claude": {
        "fresh": ["--session-id", "{SESSION_ID}", "-p", "/agenttalk.listen"],
        "resume": ["--resume", "{SESSION_ID}", "--permission-mode", "dontAsk",
                   "--allowedTools", "Bash(agenttalk *)", "-p", "/agenttalk.listen"],
    },
    "codex": {
        # Codex does NOT pin a session id at launch; a fresh launch starts with
        # the listen skill, a relaunch RESUMES the most-recent workspace session
        # (`resume --last`, documented best-effort). The skill is ALWAYS present.
        "fresh": ["-a", "never", "-s", "workspace-write", "$agenttalk-listen"],
        "resume": ["resume", "--last", "-a", "never", "-s", "workspace-write",
                   "$agenttalk-listen"],
    },
}


def _backoff_cfg(config: dict) -> dict:
    b = dict(_DEFAULTS["backoff"])
    raw = config.get("backoff") if isinstance(config.get("backoff"), dict) else {}
    for k in b:
        if isinstance(raw.get(k), (int, float)):
            b[k] = raw[k]
    return b


def session_args(cli: str, mode: str, session_id: str | None,
                 cfg_agent: dict | None = None) -> list[str]:
    """The session CLI args for a (cli, mode) launch as a LIST of literal
    tokens. ``mode`` is "fresh" or "resume". A per-agent ``session`` config
    overrides the built-in token lists. ``{SESSION_ID}`` is substituted when
    ``session_id`` is known (resume); for a fresh launch the ``{SESSION_ID}``
    token is left for the script to fill with the uuid it mints. Pure +
    deterministic - each token is one argument, so the generated command line
    is unit-testable and quote-safe."""
    cli = cli if cli in _SESSION_DEFAULTS else "claude"
    key = "fresh" if mode == "fresh" else "resume"
    tokens = _SESSION_DEFAULTS[cli][key]
    over = (cfg_agent or {}).get("session")
    if isinstance(over, dict) and isinstance(over.get(key), list):
        tokens = over[key]
    if session_id:
        return [session_id if t == "{SESSION_ID}" else t for t in tokens]
    return list(tokens)


def ps_arglist(tokens: list[str]) -> str:
    """Render tokens as a PowerShell single-quoted array-element string for an
    ``-ArgumentList @(...)`` slot: each token is a single-quoted literal (PS
    single quotes do NOT expand ``$``; embedded single quotes are doubled), so
    ``$agenttalk-listen`` stays one literal argument, never an expansion."""
    return ",".join("'" + t.replace("'", "''") + "'" for t in tokens)


def _launch_detail(st: dict, cfg_agent: dict) -> dict:
    """Resume/launch fields for a launch action. RESUME once the agent has been
    launched before - Claude pins a session_id (set by the script on a fresh
    launch); Codex doesn't pin, so a ``launched`` flag drives its resume-by-last.
    Either signal means "we've launched this agent, so resume its context".
    ``session_args`` is the token list; ``session_args_ps`` is the quote-safe PS
    array-element form the generated script splices into {SESSION_ARGS}."""
    cli = cfg_agent.get("cli", "claude")
    session_id = st.get("session_id") or None
    mode = "resume" if (session_id or st.get("launched")) else "fresh"
    tokens = session_args(cli, mode, session_id, cfg_agent)
    return {"cli": cli, "launch_mode": mode, "session_id": session_id,
            "session_args": tokens, "session_args_ps": ps_arglist(tokens)}


def build_report(store: Store, *, now_epoch: float,
                 stuck_after_seconds: float | None = None,
                 suspect_after_seconds: float | None = None,
                 state: dict | None = None) -> dict:
    """Point-in-time bus-side liveness snapshot. Read-only.

    ``protected`` is ``operator_facing`` UNION every active ``role=lead`` agent
    (fail-closed - see ``Store.protected_agents``). ``heartbeat_stale`` is True
    when there is no heartbeat or it is older than the stuck threshold
    (``stuck_after_seconds``; ``suspect_after_seconds`` accepted as a back-compat
    alias). The launched-PID liveness is NOT here - only the supervisor knows it
    - but when its ``state`` is passed, the recorded ``session_id`` (and pid) is
    merged for an operator-facing view (session_id is supervisor-local, not a
    bus fact, so it is opt-in via state).
    """
    threshold = stuck_after_seconds
    if threshold is None:
        threshold = suspect_after_seconds
    if threshold is None:
        threshold = float(_DEFAULTS["stuck_after_seconds"])
    cfg = store.load_config()
    roster = cfg.get("agents", []) or []
    roles = cfg.get("roles") or {}
    protected = store.protected_agents()
    state_agents = (state or {}).get("agents") if isinstance(state, dict) else None
    state_agents = state_agents if isinstance(state_agents, dict) else {}
    agents: dict[str, dict] = {}
    for a in roster:
        hb = store.read_heartbeat(a)
        if hb is None:
            hb_age = None
            stale = True
        else:
            hb_age = max(0.0, now_epoch - hb.timestamp())
            stale = hb_age > threshold
        marker = store.read_waiting(a)
        w_pid = marker.get("pid") if isinstance(marker, dict) else None
        w_pid = w_pid if isinstance(w_pid, int) else None
        st = state_agents.get(a) if isinstance(state_agents.get(a), dict) else {}
        agents[a] = {
            "role": roles.get(a) if isinstance(roles.get(a), str) else None,
            "protected": a in protected,
            "heartbeat_age_seconds": hb_age,
            "heartbeat_stale": stale,
            "waiting": marker is not None,
            "waiting_pid": w_pid,
            "waiting_pid_alive": bool(w_pid is not None and _process_alive(w_pid)),
            "waiting_deadline_epoch": (marker.get("deadline_epoch")
                                       if isinstance(marker, dict) else None),
            "restart_request": store.read_restart_request(a),
            "session_id": st.get("session_id"),  # supervisor-local; None unless state passed
        }
    return {
        "schema_version": 1,
        "now_epoch": now_epoch,
        "now": datetime.fromtimestamp(now_epoch, timezone.utc).isoformat().replace(
            "+00:00", "Z"),
        "roster": list(roster),
        "operator_facing": store.operator_facing(),
        "sole_lead": store.sole_lead(),
        "stuck_after_seconds": threshold,
        "agents": agents,
    }


def _plan_one(name: str, rpt: dict, st: dict, config: dict, cfg_agent: dict,
              *, now_epoch: float) -> dict:
    """Decide ONE agent's action + next state. Pure - no I/O, no clock."""
    backoff = _backoff_cfg(config)
    suspect_interval = float(config.get(
        "suspect_warn_interval_seconds", _DEFAULTS["suspect_warn_interval_seconds"]))
    reset_after = float(backoff["reset_after_seconds"])
    activity_hook = bool(cfg_agent.get("activity_hook", False))

    protected = bool(rpt.get("protected"))
    pid_alive = bool(st.get("pid_alive", False))
    marker = rpt.get("restart_request") or None
    consumed = list(st.get("consumed_rids", []))
    fails = int(st.get("consecutive_fails", 0))
    backoff_next = float(st.get("backoff_next_epoch", 0.0) or 0.0)
    healthy_since = st.get("healthy_since")
    last_warn = float(st.get("last_warn_epoch", 0.0) or 0.0)

    # carry-forward state; mutated per branch below. The supervisor-OWNED
    # fields (pid, session_id, launched) are passed THROUGH so the script can
    # persist next_state by replacement without dropping them - otherwise the
    # first healthy `none` tick would wipe pid/session_id and the supervisor
    # would relaunch a healthy agent every poll (codex blocker). On a launch
    # the script overwrites pid/session_id/launched with the new values.
    nxt = {
        "consecutive_fails": fails,
        "backoff_next_epoch": backoff_next,
        "healthy_since": healthy_since,
        "consumed_rids": consumed,
        "last_warn_epoch": last_warn,
        "pid": st.get("pid"),
        "session_id": st.get("session_id"),
        "launched": bool(st.get("launched", False)),
    }

    def _relaunch_state() -> None:
        nf = fails + 1
        delay = min(float(backoff["cap_seconds"]),
                    float(backoff["base_seconds"]) * (2 ** (nf - 1)))
        nxt["consecutive_fails"] = nf
        nxt["backoff_next_epoch"] = now_epoch + delay
        nxt["healthy_since"] = None

    def _result(action, **detail):
        res = {"agent": name, "action": action,
               "clear_marker": detail.get("clear_marker"),
               "kill_first": bool(detail.get("kill_first", False)),
               "bypass_backoff": bool(detail.get("bypass_backoff", False)),
               "notify": bool(detail.get("notify", False)),
               "reason": detail.get("reason", ""),
               "cli": None, "launch_mode": None, "session_id": None,
               "session_args": None,
               "next_state": nxt}
        if action in (RELAUNCH, STUCK_RECOVER):
            res.update(_launch_detail(st, cfg_agent))  # resume vs fresh + args
        return res

    # 1) Manual restart-request marker (highest priority).
    if isinstance(marker, dict) and isinstance(marker.get("request_id"), str):
        rid = marker["request_id"]
        forced = bool(marker.get("force_protected"))
        if protected and not forced:
            nxt["last_warn_epoch"] = now_epoch
            return _result(REFUSE_PROTECTED, clear_marker=rid, notify=True,
                           reason="restart of a protected agent requires "
                                  "--force-protected")
        if rid not in consumed:
            # Honor once: bypass backoff, kill a still-alive process first.
            nxt["consumed_rids"] = [*consumed, rid]
            _relaunch_state()
            return _result(RELAUNCH, clear_marker=rid, kill_first=pid_alive,
                           bypass_backoff=True,
                           reason=f"manual restart-request {rid}")
        # Already consumed this rid:
        if pid_alive:
            # the relaunch took - just clean up the (stale) marker.
            return _result(CLEAR_MARKER, clear_marker=rid,
                           reason=f"restart {rid} already applied; clearing marker")
        # consumed but still dead -> the relaunch FAILED. Do NOT bypass again
        # and do NOT silently clear; fall through to the backoff-gated path.

    # 2) Supervised process is dead.
    if not pid_alive:
        if protected:
            nxt["last_warn_epoch"] = now_epoch
            return _result(WARN_ONLY, notify=True,
                           reason="protected agent died - restart it manually "
                                  "(or use request-restart --force-protected)")
        if now_epoch >= backoff_next:
            _relaunch_state()
            return _result(RELAUNCH, reason="supervised process died")
        return _result(BACKOFF_WAIT,
                       reason=f"dead; backing off until {backoff_next:.0f}")

    # 3) Alive but the activity heartbeat has gone stale.
    if rpt.get("heartbeat_stale"):
        if not activity_hook:
            # No reliable activity signal -> cannot tell stuck from a healthy
            # long-turn. WARN ONLY, rate-limited; NEVER kill (the WP-2 trap).
            if now_epoch - last_warn >= suspect_interval:
                nxt["last_warn_epoch"] = now_epoch
                return _result(SUSPECT_WARN,
                               reason="heartbeat stale but NO activity hook - "
                                      "cannot confirm stuck; not killed (install "
                                      "the activity hook to enable recovery)")
            return _result(NONE, reason="suspect (no hook; warn rate-limited)")
        if protected:
            nxt["last_warn_epoch"] = now_epoch
            return _result(WARN_ONLY, notify=True,
                           reason="protected agent appears stuck - recover it "
                                  "manually (request-restart --force-protected)")
        if now_epoch >= backoff_next:
            _relaunch_state()
            return _result(STUCK_RECOVER, kill_first=True,
                           reason="alive but activity-stale -> stuck; "
                                  "kill + resume")
        return _result(BACKOFF_WAIT,
                       reason=f"stuck; backing off until {backoff_next:.0f}")

    # 4) Healthy. Advance/trip the sustained-liveness backoff reset.
    if healthy_since is None:
        nxt["healthy_since"] = now_epoch
    elif fails and (now_epoch - float(healthy_since)) >= reset_after:
        nxt["consecutive_fails"] = 0
        nxt["backoff_next_epoch"] = 0.0
    return _result(NONE, reason="healthy")


def plan_actions(report: dict, state: dict, config: dict,
                 *, now_epoch: float) -> dict:
    """The SHARED decision table. Returns ``{"now_epoch", "agents": {name: plan}}``
    where each plan has ``action`` (one of the module's action constants),
    ``clear_marker``/``kill_first``/``bypass_backoff``/``notify``/``reason``,
    and ``next_state`` for the supervisor to persist. Only agents present in
    BOTH the config and the report are planned (config drives what is
    supervised; the report supplies bus facts)."""
    cfg_agents = config.get("agents") if isinstance(config.get("agents"), dict) else {}
    rpt_agents = report.get("agents") or {}
    state_agents = state.get("agents") if isinstance(state.get("agents"), dict) else {}
    out: dict[str, dict] = {}
    for name, cfg_agent in cfg_agents.items():
        if not isinstance(cfg_agent, dict) or not cfg_agent.get("auto_restart", False):
            continue
        rpt = rpt_agents.get(name)
        if not isinstance(rpt, dict):
            continue
        st = state_agents.get(name) if isinstance(state_agents.get(name), dict) else {}
        out[name] = _plan_one(name, rpt, st, config, cfg_agent, now_epoch=now_epoch)
    return {"now_epoch": now_epoch, "agents": out}


def record_launch(state: dict, agent: str, *, cli: str, pid: int | None,
                  session_id: str | None = None) -> dict:
    """Apply a CLI's launch-SUCCESS state to ``state`` IN PLACE - the rule the
    generated script defers to Python (so it's testable, not PS-internal).
    Claude PINS the session_id it minted (resume by id); Codex pins NOTHING -
    it has no launch-time id, so its ``launched`` flag drives resume-by-last,
    and persisting a fake id would be wrong. Both mark ``pid`` + ``launched``.
    """
    agents = state.setdefault("agents", {})
    if not isinstance(agents, dict):
        agents = state["agents"] = {}
    entry = agents.get(agent)
    if not isinstance(entry, dict):
        entry = agents[agent] = {}
    entry["pid"] = pid
    entry["pid_alive"] = True
    entry["launched"] = True
    if cli == "codex":
        entry["session_id"] = None        # never persist a fake id for codex
    elif session_id:
        entry["session_id"] = session_id  # claude: pin the minted/known id
    return state


# --------------------------------------------------------------- init / scaffold

CONFIG_TEMPLATE = """\
{
  "schema_version": 1,
  "poll_seconds": 15,
  "stuck_after_seconds": 120,
  "suspect_warn_interval_seconds": 300,
  "backoff": { "base_seconds": 30, "cap_seconds": 900, "reset_after_seconds": 180 },
  "notify_sender": null,
  "notify_to": null,
  "agents": {
    "AGENT_NAME": {
      "cli": "claude",
      "auto_restart": true,
      "auto_restart_protected": false,
      "activity_hook": false,
      "cwd": "REPLACE_WITH_PROJECT_DIR",
      "env": { "AGENTTALK_SELF": "AGENT_NAME" },
      "pid_strategy": "launched-process",
      "launch": {
        "windows": "EXAMPLE (claude): Start-Process -FilePath claude.cmd -WorkingDirectory '<cwd>' -PassThru -ArgumentList @({SESSION_ARGS})",
        "_windows_codex": "EXAMPLE (codex): Start-Process -FilePath codex.cmd -WorkingDirectory '<cwd>' -PassThru -ArgumentList @('-C','<cwd>',{SESSION_ARGS})",
        "posix": "EXAMPLE (claude): setsid claude {SESSION_ARGS} >\\"$cwd/agent.log\\" 2>&1 & echo $!"
      },
      "_comment_launch": "Launch the CLI EXECUTABLE DIRECTLY (claude.cmd/codex.cmd) so the -PassThru PID dies with the agent. Do NOT wrap in 'powershell -NoExit -Command' (the wrapper outlives the agent => the supervisor watches the wrong PID). Splice {SESSION_ARGS} UNQUOTED inside -ArgumentList @(...): it is a comma-separated list of single-quoted PS literals, so '$agenttalk-listen' stays ONE argument and '$' never expands. The supervisor fills it: '--session-id','<uuid>',... on first launch, the --resume/resume-last form on relaunch.",
      "_comment_activity_hook": "Set activity_hook=true ONLY after installing the PostToolUse/Codex hook (supervise --install-activity-hook). Until then a stale heartbeat is warn-only (suspect), never a kill - so an un-instrumented agent is never mistaken for stuck."
    }
  }
}
"""

# NOTE on the templates below: the DECISION lives in Python
# (`agenttalk supervise --plan`); the scripts are THIN executors that supply
# launched-pid liveness, run the plan, and do terminal mechanics. They support
# `--once --dry-run` to print the action plan without launching anything.

PS_TEMPLATE = r"""# agenttalk supervisor (PowerShell) - generated by `agenttalk supervise --init`.
# The DECISION table is in Python (`agenttalk supervise --plan`); this script
# only tracks launched PIDs, runs the plan, and launches/kills terminals.
#   .\supervisor.ps1                 # run the monitor loop
#   .\supervisor.ps1 -Once -DryRun   # print the action plan once, change nothing
param([switch]$Once, [switch]$DryRun)
$ErrorActionPreference = 'Stop'
$Root      = Split-Path -Parent $PSScriptRoot   # the project root (.agenttalk/..)
$ConfigPath = Join-Path $PSScriptRoot 'supervisor.json'
$StatePath  = Join-Path $PSScriptRoot 'supervisor-state.json'   # SCRIPT-owned, not the bus
$cfg = Get-Content $ConfigPath -Raw | ConvertFrom-Json

function Load-State {
  if (Test-Path $StatePath) { return (Get-Content $StatePath -Raw | ConvertFrom-Json) }
  return [pscustomobject]@{ agents = [pscustomobject]@{} }
}
function Save-State($state) { $state | ConvertTo-Json -Depth 8 | Set-Content $StatePath -Encoding utf8 }
function Pid-Alive($procId) {
  if (-not $procId) { return $false }
  return [bool](Get-Process -Id $procId -ErrorAction SilentlyContinue)
}
function Launch($name, $plan) {
  $a = $cfg.agents.$name
  if (-not $a.launch.windows -or $a.launch.windows -like 'EXAMPLE*') {
    Write-Warning "supervisor: agent '$name' has no real launch.windows command - fill supervisor.json"; return $null
  }
  # {SESSION_ARGS} is the planner's PS array-of-literals string (single-quoted
  # tokens - `$` does NOT expand, each token = one argument). On a FRESH Claude
  # launch the {SESSION_ID} token is still present; mint + substitute a uuid.
  # Codex has no {SESSION_ID} (it doesn't pin), so $sid stays $null there.
  $sargs = $plan.session_args_ps
  $sid = $plan.session_id
  if ($plan.launch_mode -eq 'fresh' -and $sargs -match '\{SESSION_ID\}') {
    $sid = [guid]::NewGuid().ToString()
    $sargs = $sargs -replace '\{SESSION_ID\}', $sid
  }
  $cmd = $a.launch.windows -replace '\{SESSION_ARGS\}', $sargs
  # Launch the CLI EXECUTABLE DIRECTLY (claude.cmd/codex.cmd) via Start-Process
  # -PassThru so the monitored PID dies with the agent. Do NOT wrap in
  # `powershell -NoExit -Command` or use wt.exe - both outlive the agent, so the
  # supervisor would watch the wrong PID and loop-restart forever.
  $proc = Invoke-Expression $cmd
  if ($proc -and $proc.Id) { return @{ pid = $proc.Id; session_id = $sid } }
  Write-Warning "supervisor: launch of '$name' returned no PID (need Start-Process -PassThru); not auto-restarting it"; return $null
}

do {
  $state = Load-State
  if (-not $state.agents) { $state | Add-Member agents ([pscustomobject]@{}) -Force }
  # 1) refresh launched-pid liveness into the state the planner reads
  foreach ($name in $cfg.agents.PSObject.Properties.Name) {
    $st = $state.agents.$name; if (-not $st) { $st = [pscustomobject]@{}; $state.agents | Add-Member $name $st -Force }
    $procId = $st.pid; $st | Add-Member pid_alive (Pid-Alive $procId) -Force
  }
  Save-State $state
  # 2) ask Python for the safe action plan
  $now = [int][double]::Parse((Get-Date -UFormat %s))
  $plan = (& agenttalk --root $Root supervise --plan --state-file $StatePath --now $now) | ConvertFrom-Json
  foreach ($name in $plan.agents.PSObject.Properties.Name) {
    $p = $plan.agents.$name
    if ($DryRun) { Write-Host ("{0}: {1} - {2}" -f $name, $p.action, $p.reason); continue }
    switch ($p.action) {
      { $_ -in 'relaunch','stuck_recover' } {
        # stuck_recover kills the alive-but-stuck process first; dead-relaunch
        # has nothing to kill. Both resume the pinned session.
        if ($p.kill_first -and (Pid-Alive $state.agents.$name.pid)) { Stop-Process -Id $state.agents.$name.pid -Force -ErrorAction SilentlyContinue }
        $res = Launch $name $p
        $state.agents.$name = $p.next_state    # planner fields (passes pid/session_id/launched through)
        if ($res) {
          Save-State $state
          # Apply the launch-SUCCESS state via Python (the authoritative rule:
          # Claude pins the minted session id; Codex marks launched + NO fake
          # id). Then re-load so the in-memory state matches.
          $sidArg = @(); if ($res.session_id) { $sidArg = @('--session-id', $res.session_id) }
          & agenttalk --root $Root supervise --record-launch --for $name --cli $p.cli --pid $res.pid @sidArg --state-file $StatePath | Out-Null
          $state = Load-State
          # Clear the manual marker ONLY after a CONFIRMED relaunch (a $null
          # PID = no/invalid launch command) - never silently drop a request
          # whose relaunch failed; it must remain for the next poll to retry.
          if ($p.clear_marker) { & agenttalk --root $Root supervise --clear-restart --for $name --request-id $p.clear_marker | Out-Null }
        } else {
          Write-Warning ("supervisor: {0}: {1} FAILED (no PID) - keeping marker/state for retry" -f $name, $p.action)
        }
      }
      'clear_marker' { if ($p.clear_marker) { & agenttalk --root $Root supervise --clear-restart --for $name --request-id $p.clear_marker | Out-Null }; $state.agents.$name = $p.next_state }
      'refuse_protected' { Write-Warning ("supervisor: {0}: {1}" -f $name, $p.reason); if ($p.clear_marker) { & agenttalk --root $Root supervise --clear-restart --for $name --request-id $p.clear_marker | Out-Null }; $state.agents.$name = $p.next_state }
      { $_ -in 'warn_only','suspect_warn' } {
        Write-Warning ("supervisor: {0}: {1}" -f $name, $p.reason)
        if ($p.notify -and $cfg.notify_sender -and $cfg.notify_to) {
          & agenttalk --root $Root send --from $cfg.notify_sender --to $cfg.notify_to --kind note -m ("supervisor: {0}: {1}" -f $name, $p.reason) --quiet | Out-Null
        }
        $state.agents.$name = $p.next_state
      }
      default { $state.agents.$name = $p.next_state }
    }
  }
  if (-not $DryRun) { Save-State $state }
  if (-not $Once) { Start-Sleep -Seconds ([int]$cfg.poll_seconds) }
} while (-not $Once)
"""

def init(store: Store, *, force: bool = False) -> dict:
    """Scaffold the supervisor config + PowerShell script under ``.agenttalk/``.
    Returns ``{path: "written"|"exists"}``. Never overwrites without ``force``
    (the config especially - it holds the operator's filled-in launch commands).

    v1 ships the PowerShell supervisor only (the operator is on Windows); a
    POSIX (bash) supervisor is a documented follow-up - the Python core
    (``supervise --report``/``--plan``, ``request-restart``) is already
    cross-platform, so a future ``supervisor.sh`` is a thin add.
    """
    out: dict[str, str] = {}
    # The .ps1 is written UTF-8 with a BOM (utf-8-sig): Windows PowerShell 5.1
    # decodes a BOM-less file as Windows-1252, which corrupts any non-ASCII byte
    # and cascades into parse errors (the 0.28.1 live-test bug). The template is
    # already ASCII-only; the BOM is belt-and-suspenders and is also fine for
    # PowerShell 7+. The .json stays plain UTF-8 (a BOM would break Python's
    # json.loads when the config is read back).
    targets = [
        (store.dir / "supervisor.json", CONFIG_TEMPLATE, "utf-8"),
        (store.dir / "supervisor.ps1", PS_TEMPLATE, "utf-8-sig"),
    ]
    for path, content, encoding in targets:
        if path.exists() and not force:
            out[str(path)] = "exists"
            continue
        path.write_text(content, encoding=encoding)
        out[str(path)] = "written"
    return out


# ---- activity-hook install (opt-in; unlocks stuck_recover) -----------------
#
# The hook runs `agenttalk heartbeat` on every tool call (it resolves the agent
# from $AGENTTALK_SELF and is throttled, so it's a dumb one-liner). It is what
# makes "stale heartbeat == genuinely stuck" true; until it's installed,
# activity_hook stays false and a stale heartbeat is only a warn (never a kill).

ACTIVITY_HOOK_COMMAND = "agenttalk heartbeat"


def claude_hook_snippet() -> str:
    """The PostToolUse fragment to paste into a project .claude/settings.json."""
    return json.dumps({"hooks": {"PostToolUse": [
        {"matcher": "*", "hooks": [
            {"type": "command", "command": ACTIVITY_HOOK_COMMAND}]}]}}, indent=2)


def _merge_post_tool_use_hook(settings: dict) -> bool:
    """Add the heartbeat PostToolUse hook to a settings dict IN PLACE, in the
    matcher-GROUP shape both Claude and Codex use ({"matcher","hooks":[...]}),
    preserving every existing key/group. Returns True if it changed anything
    (False = already present, idempotent). The presence-check scans the NESTED
    hooks of every group so a correctly-shaped existing hook isn't duplicated."""
    hooks = settings.setdefault("hooks", {})
    groups = hooks.setdefault("PostToolUse", [])
    if not isinstance(groups, list):
        return False  # malformed - refuse to touch
    for g in groups:
        for h in (g.get("hooks", []) if isinstance(g, dict) else []):
            if isinstance(h, dict) and h.get("command") == ACTIVITY_HOOK_COMMAND:
                return False  # already installed
    groups.append({"matcher": "*", "hooks": [
        {"type": "command", "command": ACTIVITY_HOOK_COMMAND}]})
    return True


def install_activity_hook(store: Store, *, claude: bool = True,
                          codex: bool = False) -> dict:
    """MERGE the activity-heartbeat hook into PROJECT-scoped config files -
    ``.claude/settings.json`` and/or ``.codex/hooks.json`` under the project
    root. NEVER touches global ~/.claude or ~/.codex, NEVER clobbers existing
    hooks/keys (idempotent). Returns ``{path: "installed"|"already"|"skipped"}``.
    """
    out: dict[str, str] = {}
    if claude:
        p = store.root / ".claude" / "settings.json"
        settings = {}
        if p.exists():
            try:
                settings = json.loads(p.read_text(encoding="utf-8")) or {}
            except (ValueError, OSError):
                out[str(p)] = "skipped (unreadable - merge by hand)"
                settings = None
        if settings is not None:
            changed = _merge_post_tool_use_hook(settings)
            if changed:
                p.parent.mkdir(parents=True, exist_ok=True)
                p.write_text(json.dumps(settings, indent=2), encoding="utf-8")
            out[str(p)] = "installed" if changed else "already"
    if codex:
        # Codex uses the SAME matcher-group PostToolUse shape as Claude (a
        # flat {type,command} would mis-install and the presence-check would
        # duplicate a correctly-shaped existing hook -> a safety bug if
        # activity_hook is then trusted). .codex/hooks.json (JSON).
        p = store.root / ".codex" / "hooks.json"
        cfg = {}
        if p.exists():
            try:
                cfg = json.loads(p.read_text(encoding="utf-8")) or {}
            except (ValueError, OSError):
                out[str(p)] = "skipped (unreadable - merge by hand)"
                cfg = None
        if cfg is not None:
            changed = _merge_post_tool_use_hook(cfg)
            if changed:
                p.parent.mkdir(parents=True, exist_ok=True)
                p.write_text(json.dumps(cfg, indent=2), encoding="utf-8")
            out[str(p)] = "installed" if changed else "already"
    return out
